### PR TITLE
Final Changes 2/2

### PR DESCRIPTION
**Pull request by BashirKad**
I'll keep this one short, but this is obviously the GUI for everything. I changed most things to take JOptionPanes instead of Scanners which has the added benefit of being less error prone. As always, if I'm missing anything please tell me

Oh also, I did very few comments so sorry about that

### CODE REVIEW

**Comment by MariaMa-GitHub** [comment]
@BashirKad @bobyangg @actualbobbernauts Damn we forgot the documentation

**Comment by BashirKad** [comment]
I'm honestly still confused about the documentation. Is it supposed to be done by each of us separately? One on the overall "success" of our plan vs final product and one on how we all worked?

**Comment by MariaMa-GitHub** [comment]
Eum that's two separate things. The documentation is part of the project and the report is what the teacher is going to grade us on.

1. Documentation: explains how the program works (user manual)
2. Report (two parts):
    - project management (e.g., compare plan to actual performance, outline successes, make recommendations for improvement) 
    - team performance (evaluation of all 4 team members but **NOT REVEALING ANY NAMES**)

**Comment by BashirKad** [comment]
Okay, in that case I just added the documentation, but it's not in the latest pull request. Once everyone agrees on the one I did like 40m ago, I'll make one more commit to add that.

**Comment by MariaMa-GitHub** [comment]
@BashirKad So in the documentation it's supposed to be something like:

This is how the library system works: 
1. Answer whether or not you have a library account
2. If yes: enter your library card number.
2. If no: create an account.

...

**Comment by BashirKad** [comment]
Oh is that how she wanted it? I just outlined what the program could do in simple terms. Just a very easy user manual

**Comment by MariaMa-GitHub** [comment]
Well I mean she didn't specify to what degree of precision it has to be but I guess that at least, by reading the user manual, the user should be able to go through all the steps without getting confused.

**Comment by BashirKad** [comment]
yeah I think we'll be fine then

**Comment by actualbobbernauts** [comment]
Think everything looks good to merge.

**Comment by BashirKad** [comment]
@bobyangg any comments before we merge?

**Comment by MariaMa-GitHub** [comment]
@BashirKad I am currently testing your code and there is one thing I wanna ask real quick. Is it just me or I can only see like half of the text on the buttons?

**Comment by bobyangg** [comment]
> @bobyangg any comments before we merge?
No looks good

**Comment by BashirKad** [comment]
If you're running in BlueJ, it's probably just BlueJ being bad. I don't know why but BlueJ messes up a lot of the dimensions for things especially around the edges/corners. Everything was fine when I used eclipse

**Comment by BashirKad** [comment]
> 

Alright, I'm merging now, then making one more commit on top of that to add the documentation

**Comment by MariaMa-GitHub** [comment]
@BashirKad kk then I think your code is alright. Just use this instead of your findPerson and findMedia methods:

public Person findPerson(int target)
    {
    	for (Person person : this.people)
    	{
            	if (person.cardNum == target)
            	{
            		return person;
            	}
    	}
    	return null; //no match found
    }
    public Media findMedia(String target)
    {
    	for (Media item : this.collection)
    	{
    		if (item.equals(target))
    		{
    			return item;
    		}
    	}
    
    	return null; //no match found
    }

**Comment by BashirKad** [comment]
alright, I'll change that in the new commit aswell

**Pull request merged**
