### PR TITLE
should output the error message now

### PR DESCRIPTION
**Pull request by actualbobbernauts**

### CODE REVIEW

**Review by MariaMa-GitHub — CHANGES_REQUESTED** [review]
@actualbobbernauts yeah it works but you didn't skip the "which items would you like to borrow" part. You can make the printFilteredCollection() method return a boolean (true if genre found and false otherwise) and based on that boolean execute the "which items would you like to borrow" code (e.g. only if not error execute code)

**Comment by actualbobbernauts** [comment]
@MariaMa-GitHub it should ACTUALLY work now

**Comment by MariaMa-GitHub** [comment]
@actualbobbernauts kk I have committed to the main with your changes + some other small changes of mine. You can run it to make sure everything works as expected (I tried it on my end it should work fine.

**Comment by actualbobbernauts** [comment]
@MariaMa-GitHub Looks good.

**Comment by BashirKad** [comment]
same with this, just gonna close it

**Pull request closed without merging**
