### PR TITLE
Sorting by media type + equals method + id variable changes

### PR DESCRIPTION
**Pull request by bobyangg**

### CODE REVIEW

**Review by MariaMa-GitHub — APPROVED** [review]
I am fine with your pull request as long as the person.java class is deleted

**Comment by bobyangg** [comment]
> I am fine with your pull request as long as the person.java class is deleted

Yea you can delete that class no edits were made to it

**Comment by MariaMa-GitHub** [comment]
@BashirKad @actualbobbernauts are you all ok with his edits?

**Comment by BashirKad** [comment]
I don't see any problems with the edits, my previous stuff is all still there and everything we discussed together looks good. Whenever you guys want just make the merge

**Pull request merged**
